swagger: '2.0'
info:
  description: Cette API retourne les données de droits à une couverture assurance maladie de l'utilisateur authentifié via France Connect par un fournisseur de services.
    
    
    L'API retourne également les droits des bénéficiaires de cet utilisateur.
    
    
    Il est important de noter que cette API ne restitue les droits que des bénéficiaires connus du régimes général et des régimes hebergés dans les SI du régime général ( CNMSS, CAMIEG, MNH, CAVIMAC...). Il ne sera donc pas possible de connaître les droits de bénéficaires de la MSA, MGEN et du RSI, pour ce dernier dans l'attente de son  intégration au régime général.
    
    
    L'API est accèdée après une connexion France Connect réussie.
    
    
    La recherche se fait par fourchette de dates, mais à partir de la date d'appel, ainsi ; il n'est pas possible de chercher des informations sur un bénéficiaire à une date antérieure à celle de la date d'interrogation. De même les dates de fin de droits et de contrats  sont connus au maximum un an après le date d'appel de l'API. 

  contact:
    email: contact-api-partenaire@ameli.fr
  title: API des droits assurés
  version: v1
host: partenaires.api.ameli.fr
basePath: /test/v1/droits/beneficiaires
schemes:
  - https
security:
  - APIKeyHeader: []
  - OAuth2: [droits_assurance_maladie]
securityDefinitions:
   APIKeyHeader:
     type: apiKey
     in: header
     name: X-API-Key
   OAuth2:
    type: oauth2
    flow: accessCode
    description: https://partenaires.franceconnect.gouv.fr/fcp/fournisseur-service#sign_in
    authorizationUrl: https://fcp.integ01.dev-franceconnect.fr/api/v1/authorize
    tokenUrl: https://fcp.integ01.dev-franceconnect.fr/api/v1/token
    scopes:
      droits_assurance_maladie: scope de consentement de l'utilisateur France Connect
paths:
  /me:
    get:
      tags:
        - beneficiaire
      summary: Retourne les données bénéficaire
      description: Retroune le détail des données bénéficiaires de l'utilisateur connecté via France Connect.
      operationId: getMe
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: dateDebut
          in: query
          description: Début de la plage de recherche des données du bénéficiaire. Date du jour si non précisée.
          required: false
          type: string
          format: date
        - name: dateFin
          in: query
          description: Fin de la plage de recherche des données du bénéficiaire. dateDebut + 1 an si non précisée.
          required: false
          type: string
          format: date
      responses:
        '200':
          description: OK. Utilisateur authentifié auprès de France Connect et données bénéficiaires trouvées.
          schema:
            $ref: '#/definitions/Beneficiaire'
  /me/beneficiaires:
    get:
      tags:
        - beneficiaire
      summary: Retourne la liste des bénéficiaires de l'utilisateur connecté via France Connect.
      operationId: getBeneficiaires
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: dateDebut
          in: query
          description: Début de la plage de recherche des données du bénéficiaire. Date du jour si non précisée.
          required: false
          type: string
          format: date
        - name: dateFin
          in: query
          description: Fin de la plage de recherche des données du bénéficiaire. dateDebut + 1 an si non précisée.
          required: false
          type: string
          format: date
      responses:
        '200':
          description: OK. Utilisateur authentifié auprès de France Connect et données bénéficiaires trouvées.
          schema:
            type: array
            items:
              $ref: '#/definitions/Beneficiaire'
  '/':
    get:
      tags:
        - beneficiaire
      summary: Retourne les données d'un bénéficiaire identifié par son NIR associé à l'utilisateur connecté via France Connect.
      operationId: getBeneficiairesNir
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: nir
          in: header
          description: NIR d'un bénéficiaire de l'assuré authentifié via France Connect
          required: true
          type: string
        - name: dateDebut
          in: query
          description: Début de la plage de recherche des données du bénéficiaire. Date du jour si non précisée.
          required: false
          type: string
          format: date
        - name: dateFin
          in: query
          description: Fin de la plage de recherche des données du bénéficiaire. dateDebut + 1 an si non précisée.
          required: false
          type: string
          format: date
      responses:
        '200':
          description: OK. Utilisateur authentifié auprès de France Connect et données bénéficiaires trouvées.
          schema:
            $ref: '#/definitions/Beneficiaire'
  '/caisse':
    get:
      tags:
        - beneficiaire
      summary: Retourne le détail de l'organisme de rattachement d'un bénéficiaire; régime, caisse , centre de gestion, adresse postale de la caisse. 
      operationId: getBeneficiairesNirCaisse
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: nir
          in: header
          description: NIR d'un bénéficiaire de l'assuré authentifié via France Connect
          required: true
          type: string
        - name: dateDebut
          in: query
          description: Début de la plage de recherche des données du bénéficiaire. Date du jour si non précisée.
          required: false
          type: string
          format: date
        - name: dateFin
          in: query
          description: Fin de la plage de recherche des données du bénéficiaire. dateDebut + 1 an si non précisée.
          required: false
          type: string
          format: date
      responses:
        '200':
          description: OK. Utilisateur authentifié auprès de France Connect et données de complémentaire santé trouvées.
          schema:
            $ref: '#/definitions/Caisse'
  '/contrats':
    get:
      tags:
        - beneficiaire
      summary: Retourne la liste des contrats de base (AMO) et complémentaires (AMC) (dans cette version de l'API uniquement CMUC ou ACS)
      operationId: getBeneficiairesNirContrats
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: nir
          in: header
          description: NIR d'un bénéficiaire de l'assuré authentifié via France Connect
          required: true
          type: string
        - name: dateDebut
          in: query
          description: Début de la plage de recherche des données du bénéficiaire. Date du jour si non précisée.
          required: false
          type: string
          format: date
        - name: dateFin
          in: query
          description: Fin de la plage de recherche des données du bénéficiaire. dateDebut + 1 an si non précisée.
          required: false
          type: string
          format: date
      responses:
        '200':
          description: OK. Utilisateur authentifié auprès de France Connect et données contrat trouvées.
          schema:
            type: array
            items:
              $ref: '#/definitions/Contrat'
  '/exonerations':
    get:
      tags:
        - beneficiaire
      summary: Retourne la liste des exonérations. Le motif d'une exonération n'est accessible qu'aux etablissements de soins.
      operationId: getBeneficiairesNirExonerations
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: nir
          in: header
          description: NIR d'un bénéficiaire de l'assuré authentifié via France Connect
          required: true
          type: string
        - name: dateDebut
          in: query
          description: Début de la plage de recherche des données du bénéficiaire. Date du jour si non précisée.
          required: false
          type: string
          format: date
        - name: dateFin
          in: query
          description: Fin de la plage de recherche des données du bénéficiaire. dateDebut + 1 an si non précisée.
          required: false
          type: string
          format: date
      responses:
        '200':
          description: OK. Utilisateur authentifié auprès de France Connect et données d'exonérations trouvées.
          schema:
            type: array
            items:
              $ref: '#/definitions/Exoneration'
  '/medecin-traitant':
    get:
      tags:
        - beneficiaire
      summary: Retourne les données d'un médecin traitant d'un bénéficiaire. A noter il se peut qu'en fonction des  dates d'interrogation le contrat médecin traitant soit échu, cela arrive notamment quand une date de cessation d'activité du médecin est postionnée dans le futur par rapport à la date d'interrogation du contrat actif.
      operationId: getBeneficiairesNirMedecinTraitant
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: nir
          in: header
          description: NIR d'un bénéficiaire de l'assuré authentifié via France Connect
          required: true
          type: string
        - name: dateDebut
          in: query
          description: Début de la plage de recherche des données du bénéficiaire. Date du jour si non précisée.
          required: false
          type: string
          format: date
        - name: dateFin
          in: query
          description: Fin de la plage de recherche des données du bénéficiaire. dateDebut + 1 an si non précisée.
          required: false
          type: string
          format: date
      responses:
        '200':
          description: OK. Utilisateur authentifié auprès de France Connect et données médecin traitant trouvées.
          schema:
            $ref: '#/definitions/MedecinTraitant'
definitions:
  Adresse:
    type: object
    properties:
      code_postal:
        type: string
        example: '49100'
        description: 'Ligne 6 : Informations d''acheminement. Code postal ou code CEDEX (Courrier d''Entreprise à Distribution EXceptionnelle).'
      commune:
        type: string
        example: Angers
        description: 'Ligne 6 : Informations d''acheminement. Nom de la localité du destinataire, ou libellé du bureau distributeur CEDEX (dans ce cas, présence obligatoire de l''attribut Cedex).'
      complement_adresse:
        type: string
        description: 'Ligne 3 : Complément au point géographique. Accès au bâtiment, bâtiment, ensemble immobilier.'
      destinataire:
        type: string
        example: Audrey Fournier
        description: 'Ligne 1 : Prénom et nom d''usage pour un bénéficiaire. Raison sociale pour une caisse.'
      indice_repetition:
        type: string
        example: Bis
        description: 'Ligne 4 : Point géographique. Extension du numéro dans la voie sous forme littérale (Bis, Ter, Quater, etc. ) ou codée (B, T, Q, C etc.). Il peut également s''agir d''une simple lettre (A, B, C, etc.).'
      mention_distribution:
        type: string
        example: BP
        description: 'Ligne 5 : Mention particulière de distribution. BP, Poste Restante, TSA (Tri Service Arrivée), AUTORISATION etc., suivie du libellé de la localité de destination dans le cas ou celle-ci serait différente du libellé CEDEX, lieu dit ou hameau.'
      nom_voie:
        type: string
        example: Charles de Gaule
        description: 'Ligne 4 : Point géographique. Nom ou libellé de la voie.'
      numero_voie:
        type: string
        example: '13'
        description: 'Ligne 4 : Point géographique. Numéro dans la voie.'
      point_remise:
        type: string
        example: Appartement 24
        description: 'Ligne 2 : Identité du domicilié (mention ''chez''), numéro de boite aux lettres ou d''appartement, escalier, étage, CIDEX (Courrier Individuel à Distribution EXceptionnelle), etc. Destinataire personne morale : identité de la personne destinataire, direction, service, numéro de l''étage, bureau, etc.'
      type_voie:
        type: string
        example: boulevard
        description: 'Ligne 4 : Point géographique. Donne la nature de voie sous forme littérale, abrégée, ou codée.'
    description: Adresse au format AFNOR XP Z 10-011.
  Beneficiaire:
    type: object
    properties:
      date_naissance:
        type: string
        format: date
      medecin_traitant_choisi:
        type: boolean
        example: false
      nir:
        type: string
        description: NIR du bénéficiaire
      nom_famille:
        type: string
      nom_usage:
        type: string
      prenom:
        type: string
      presence_CMUC_ACS:
        type: boolean
        example: false
      qualite:
        type: string
        description: Précision du type de bénéficiaire
        enum:
          - assure
          - concubin
          - concubin_en_rupture
          - pacse
          - ex_pacse
          - conjoint
          - conjoint_separe
          - conjoint_divorce
          - conjoint_veuf
          - parent
          - enfant
          - autre
      rang_naissance:
        type: integer
        format: int32
        description: Permet de distinguer les jumeaux
  Caisse:
    type: object
    properties:
      adresse:
        $ref: '#/definitions/Adresse'
      codeCentre:
        type: string
      grandRegime:
        type: string
      id:
        type: string
        example: '01261'
        description: 'Identifiant inter-régime de la caisse. Concaténation du code grand-régime (2 car.), du code caisse (3 car.)'
      libelle:
        type: string
      organisme:
        type: string
  Contrat:
    type: object
    properties:
      date_debut:
        type: string
        format: date
        example: '2020-01-15'
        description: Date de début pour un contrat qui commence dans le futur.Les contrats complémentaires santé ne sont pas disponibles dans cette version de l'API
      date_fin:
        type: string
        format: date
        example: '2025-01-15'
      details:
        $ref: '#/definitions/ContratDetails'
      nature_assurance:
        type: string
        description: Assurance Maladie obligatoire (AMO) ou complémentaire (AMC)
        enum:
          - AMO
          - AMC
      periodes_droits:
        type: array
        description: Liste des périodes de droits du contrat
        items:
          $ref: '#/definitions/ContratPeriodesDroits'
  ContratDetails:
    type: object
    properties:
      code_type_contrat:
        type: string
        example: BASE
        description: code identifiant le type de contrat
      libelle_type_contrat:
        type: string
        example: Droits de base (contrat sans spécificité)
        description: signification associée au code identifiant le type de contrat
    description: Détails sur le type de contrat
  ContratPeriodesDroits:
    type: object
    properties:
      date_debut:
        type: string
        format: date
        example: '2021-01-01'
      date_fin:
        type: string
        format: date
        example: '2022-01-01'
  Exoneration:
    type: object
    properties:
      date_debut:
        type: string
        format: date
        example: '2021-01-01'
        description: Date de début pour une exonération qui commence dans le futur
      date_fin:
        type: string
        format: date
        example: '2022-01-01'
      maternite:
        $ref: '#/definitions/ExonerationMaternite'
      motif:
        $ref: '#/definitions/ExonerationMotif'
  ExonerationMaternite:
    type: object
    properties:
      date_presumee_grossesse:
        type: string
        format: date
        example: '2020-02-14'
      date_reelle_accouchement:
        type: string
        format: date
        example: '2021-11-14'
  ExonerationMotif:
    type: object
    properties:
      code:
        type: string
        description: 'Nature de l''exonération du ticket modérateur. Valeurs possibles : INV (petits régimes exonérants : invalides), MAT (maternité), LIS, EXP, EXC, A115_DET_PML (Article 115 / Détenu / Pensionnés : G.I.G, AVEUGLES-RESIS, SAPEURS-POMP-INVA), NE (nouveau né), STE (stérilité), EDS (éducation spécialisée)'
        enum:
          - INV
          - MAT
          - LIS
          - EXP
          - EXC
          - A115_DET_PML
          - NE
          - STE
          - EDS
      libelle:
        type: string
      libelle_long:
        type: string
  MedecinTraitant:
    type: object
    properties:
      date_debut:
        type: string
        format: date
      date_fin:
        type: string
        format: date
      nom:
        type: string
      numero_am:
        type: string
      prenom:
        type: string
